server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8 

spring:
  security:
#    user:
#      name: test
#      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 962248784598-i86dasman6qsis3rrvfo91ng9gqllt4l.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: D38yczwW3oMwKj1w7Rxu
            client-secret: zYrjLmC3CG
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider: 
         naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri:  https://openapi.naver.com/v1/nid/me
           user-name-attribute: response


  mvc:
    static-path-pattern: /static/**
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:8001/board?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: toor
    
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/D_junil/jihun/workspace/git/security_jihun/upload/